import 'package:flutter/material.dart';
import 'model.dart';
const List<Content> featured=[
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500.00",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
      DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"The Complete Digital Marketing Course",
      author:"Rob Percival Daragh Walsh",
      price:"500.00",
      rating:"4.4",
      tag:"Bestseller",
      enrolled:"{117565}",
    DetailedDescription:"With over 20 hours of training, quizzes and practical steps and you can follow -this is one of the most comprehensive digital marketing courses available",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
];
const List<Content> top=[
  Content(
      image:"assets/banner.jpg",
      title:"The Complete 2020 Web Development Bootcamp",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
  Content(
      image:"assets/unnamed.png",
      title:"Microsoft Excel-Excel from Beginner to Advanced",
      author:"Kyle Pew,office Newb LLc",
      price:"500",
      rating:"5",
      tag:"Bestseller",
      enrolled:"{123456}",
    DetailedDescription:"",
  ),
];