// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyTgqC6oSEJ4fDBbl_5XU_HE_xXZ1KEIw',
    appId: '1:51426142609:web:3ce67b4e2d22bdf1c2d230',
    messagingSenderId: '51426142609',
    projectId: 'learner-dc59e',
    authDomain: 'learner-dc59e.firebaseapp.com',
    storageBucket: 'learner-dc59e.appspot.com',
    measurementId: 'G-672RV80M95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2urN3R4FOwTk4OdSgmQSxUd-_JNqSAHY',
    appId: '1:51426142609:android:cf8ce0b19f92bee3c2d230',
    messagingSenderId: '51426142609',
    projectId: 'learner-dc59e',
    storageBucket: 'learner-dc59e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF6K9jBri4re-oM4t4vm1RgOE32kfOqws',
    appId: '1:51426142609:ios:891e0fa7b8c6f702c2d230',
    messagingSenderId: '51426142609',
    projectId: 'learner-dc59e',
    storageBucket: 'learner-dc59e.appspot.com',
    iosClientId: '51426142609-ac5m58qc3n6q861k2l9lrinf9s7op1cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.elearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF6K9jBri4re-oM4t4vm1RgOE32kfOqws',
    appId: '1:51426142609:ios:506ccc57c688c9aac2d230',
    messagingSenderId: '51426142609',
    projectId: 'learner-dc59e',
    storageBucket: 'learner-dc59e.appspot.com',
    iosClientId: '51426142609-limf4mdniqquuntvu9rocu3jdduif5fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.elearning.RunnerTests',
  );
}
